//
//  Localizable.h
//  EAMovieApp
//
//  Created by EastAgile42 on 8/15/17.
//  Copyright © 2017 East Agile. All rights reserved.
//

FOUNDATION_EXPORT NSString *const EMAIL_TEXT;
FOUNDATION_EXPORT NSString *const PASSWORD_TEXT;

FOUNDATION_EXPORT NSString *const SIGNIN_BUTTON_TITLE;
FOUNDATION_EXPORT NSString *const SIGNUP_BUTTON_TITLE;
FOUNDATION_EXPORT NSString *const SKIP_BUTTON_TITLE;
FOUNDATION_EXPORT NSString *const CANCEL_BUTTON_TITLE;
FOUNDATION_EXPORT NSString *const FORGOT_PASSWORD_BUTTON_TITLE;
